# Example workflow that comments AI scan results on pull requests
# Place this file in .github/workflows/ai-scan-pr.yml in your repository

name: AI Scan PR Comment
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  scan-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Scan for AI models
        id: ai-scan
        uses: hiddenlayerai/hl-scai@main
        with:
          directory: .
          huggingface-token: ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const modelsFound = ${{ steps.ai-scan.outputs.models-found }};
            const summary = `${{ steps.ai-scan.outputs.summary }}`;

            let emoji = '✅';
            let status = 'No AI models detected';

            if (modelsFound > 0) {
              emoji = '🤖';
              status = `Found ${modelsFound} AI model(s)`;
            }

            const comment = `## ${emoji} AI Model Scan Results

            **Status:** ${status}

            ${summary}

            <details>
            <summary>📋 View detailed report</summary>

            \`\`\`json
            ${{ steps.ai-scan.outputs.ai-assets }}
            \`\`\`
            </details>

            ---
            *Scanned by [HL-SCAI](https://github.com/hiddenlayerai/hl-scai) at ${new Date().toISOString()}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
